### ISSUE TITLE
Update Cake.Core reference

### ISSUE THREAD

**Issue by laurentkempe** [cake-contrib/cake-ndepend#23]
Update Cake.Core reference so that the build log doesn't show 

	The assembly 'Cake.NDepend, Version=1.2.0.0' is referencing an older version of Cake.Core (0.26.0)

Update it to 0.33.0 following recommendation on [Supported Cake Version](https://github.com/cake-contrib/Home/blob/master/Guidelines.md#supported-cake-version)

**Comment by joaoasrosa** [comment]
Thanks!
